

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    restart: always
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk-network
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: fluentd:24224
    #     tag: kibana
    # dns:
    #   - 127.0.0.1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    restart: always
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk-network
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: fluentd:24224
    #     tag: kibana
    # dns:
    #   - 127.0.0.1

  fluentd:
    image: fluent/fluentd:v1.16-1
    container_name: fluentd
    environment:
      - FLUENT_ELASTICSEARCH_HOST=elasticsearch
      - FLUENT_ELASTICSEARCH_PORT=9200
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers
      - ./files:/fluentd/log/files
      - ./configurations:/fluentd/etc/
      - ./logs:/output/
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - elk-network
    # dns:
    #   - 127.0.0.1
      

  # zipkin:
  #   image: openzipkin/zipkin:2.24
  #   container_name: zipkin
  #   environment:
  #     - STORAGE_TYPE=elasticsearch
  #     - ES_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - "9411:9411"
  #   networks:
  #     - elk-network

volumes:
  es_data:
    driver: local
  fluentd_data:
    driver: local

networks:
  elk-network:
    driver: bridge
