apiVersion: apps/v1
kind: Deployment
metadata:
  name: vatrinah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vatrinah
  template:
    metadata:
      labels:
        app: vatrinah
    spec:
      containers:
      - name: vatrinah
        image: hesh3am/vatrinahcomingsoon
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vatrinah
spec:
  selector:
    app: vatrinah
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
