apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
      - name: taskapp
        image: hesh3am/taskapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskapp
spec:
  selector:
    app: taskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
