apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webserver
spec:
  replicas: 6
  selector:
    matchLabels:
      app: k8s-webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-webserver
    spec:
      containers:
      - name: k8s-webserver
        image: hesh3am/k8s-webserver
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-webserver
spec:
  selector:
    app: k8s-webserver
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
